spring.application.name=usuarios

# Configuración PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/usuarios_db
spring.datasource.username=postgres
spring.datasource.password=Admin123

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Para que dure solo 1 hora (3600000 ms):
jwt.expiration=3600000